# Generated by Django 4.1.2 on 2022-11-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Familia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=30)),
                ("relacion", models.CharField(max_length=30)),
                ("edad", models.IntegerField()),
                ("fecha_de_nacimiento", models.DateField()),
                ("email", models.CharField(max_length=20)),
                ("profesion", models.CharField(max_length=20)),
            ],
        ),
    ]
